In [1]:
import numpy as np
from PIL import Image

In [12]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [20]:
np.random.randint(10, size=10)

array([3, 7, 0, 6, 5, 1, 9, 3, 6, 1])

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

In [23]:
arr = np.zeros([2, 3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr = np.ones([2, 3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(arr[[0, 1, 2, 3], [0, 0, 1, 2]])

[ 0  3  7 11]


In [70]:
arr1 = np.array([[0, 1], [2, 3]])
arr2 = arr1.copy()
arr = np.concatenate((arr1, arr2), axis=0)
arrw = np.concatenate((arr1, arr2), axis=1)
print(arr)
print(arrw)

[[0 1]
 [2 3]
 [0 1]
 [2 3]]
[[0 1 0 1]
 [2 3 2 3]]


In [62]:
arr = np.arange(20)
arr = arr.reshape(5, 4)
print(arr)
arr[[0, 1], [0, 1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([0, 5])

In [71]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.stack((arr1, arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
arr = np.arange(1, 7)
arrw = np.array_split(arr, 3)
arrw

[array([1, 2]), array([3, 4]), array([5, 6])]


In [74]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
arrw = np.hsplit(arr, 3)
for i in arrw:
    print(i, end="\n\n")

[[0]
 [3]
 [6]]

[[1]
 [4]
 [7]]

[[2]
 [5]
 [8]]



In [69]:
arrw = np.vsplit(arr, 3)
for i in arrw:
    print(i, end="\n\n")

[[0 1 2]]

[[3 4 5]]

[[6 7 8]]



In [7]:
image = Image.open('w.jpg')
image_arr = np.array(image)
flip_arr = np.flip(image_arr, 0)
image_arr = image_arr[700:1400, 1450:2361]
flip_arr = np.flip(image_arr, 0)
image = Image.fromarray(image_arr)
imagew = Image.fromarray(flip_arr)
image.show()
imagew.show()